data:
  data_path: ""
  acc: 4
  acs: 24
  mask: uniform # choices: [random, uniform]

model:
  # R
  num_cascades: 10
  num_layers: 6
  num_filters: 64
  kernel_size: 3
  instance_norm: false
  # DC
  mu: 0.5
  cg_iter: 10

train:
  device: 3

  dataloader_args:
    num_workers: 8
    batch_size: 16

  num_epochs: 100

  criterion: L1L2Loss
  criterion_args: {}

  optimizer: Adam
  optimizer_args:
    lr: 0.00005
    betas:
      - 0.9
      - 0.999
    weight_decay: 0.000001
  

  scheduler: ReduceLROnPlateau
  scheduler_args:
    factor: 0.1
    patience: 5
    threshold_mode: rel
    threshold: 0.0001
    min_lr: 0
    verbose: True

  early_stop: 15

  output_path: ../logs/x4_uniform_l1l2_vs
